### ISSUE TITLE
Do not include access-date field when doi field is included

### ISSUE THREAD

**Issue by AndreasLoow** [5j9/yadkard#7] opened 2017-05-21 08:01 UTC
Similarly to #6, I don't think an access-date is needed if a DOI is present:

> [Access-date] is not required for linked documents that do not change. For example, access-date is not required for links to copies of published research papers accessed via DOI or a published book, [...] -- https://en.wikipedia.org/wiki/Help:Citation_Style_1

But I think the title of this issue is an oversimplification, because it might be the case that a DOI points to something that might change... I'm not sure. But the condition "DOI included and the citation type is one of {book, conference, journal, report, techreport, thesis}" should be safe I think.

**Comment by 5j9** [comment] 2017-05-23 07:17
In Wikipedia citation templates, access-date is only valid if a URL is provided. So I guess this can be considered a duplicate of #6 because if we remove the URL, we'll have to also remove the access-date.

**Closed by 5j9** 2017-05-23 07:17 UTC
